import { CategoryType } from "@shared/types/types";

export const jeopardyTemplate: CategoryType[] = [
  {
    name: "Easy Questions",
    questions: [
      {
        value: 200,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 400,
        question: "Identify this song.",
        answer: "What is [Song Name]?",
        type: "audio",
        mediaUrl: "https://example.com/audio1.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 600,
        question: "What is shown in this image?",
        answer: "What is [Image Description]?",
        type: "image",
        mediaUrl: "https://example.com/image1.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 1000,
        question: "Watch this clip and answer the question.",
        answer: "What is [Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video1.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Hard Questions",
    questions: [
      {
        value: 200,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 400,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 600,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 1000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Other Questions",
    questions: [
      {
        value: 200,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 400,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 600,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 1000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Super Hard Questions",
    questions: [
      {
        value: 200,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 400,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 600,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 1000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Insane Questions",
    questions: [
      {
        value: 200,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 400,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 600,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 1000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Softballs",
    questions: [
      {
        value: 200,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 400,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 600,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 1000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
];

export const doubleJeopardyTemplate: CategoryType[] = [
  {
    name: "Easy Questions",
    questions: [
      {
        value: 400,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "Identify this song.",
        answer: "What is [Song Name]?",
        type: "audio",
        mediaUrl: "https://example.com/audio1.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1200,
        question: "What is shown in this image?",
        answer: "What is [Image Description]?",
        type: "image",
        mediaUrl: "https://example.com/image1.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1600,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 2000,
        question: "Watch this clip and answer the question.",
        answer: "What is [Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video1.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Hard Questions",
    questions: [
      {
        value: 400,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1200,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1600,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 2000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Other Questions",
    questions: [
      {
        value: 400,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1200,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1600,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 2000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Super Hard Questions",
    questions: [
      {
        value: 400,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1200,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1600,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 2000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Insane Questions",
    questions: [
      {
        value: 400,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1200,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1600,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 2000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
  {
    name: "Softballs",
    questions: [
      {
        value: 400,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: false,
        answered: false,
      },
      {
        value: 800,
        question: "Identify this sound clip.",
        answer: "What is [Sound Answer]?",
        type: "audio",
        mediaUrl: "https://example.com/audio2.mp3",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1200,
        question: "What location is shown in this image?",
        answer: "What is [Location Name]?",
        type: "image",
        mediaUrl: "https://example.com/image2.jpg",
        dailyDouble: false,
        answered: false,
      },
      {
        value: 1600,
        question: "This is an answer",
        answer: "What is the question?",
        type: "text",
        mediaUrl: null,
        dailyDouble: true,
        answered: false,
      },
      {
        value: 2000,
        question: "Watch this clip and answer.",
        answer: "What is [Video Answer]?",
        type: "video",
        mediaUrl: "https://example.com/video2.mp4",
        dailyDouble: false,
        answered: false,
      },
    ],
  },
];
